
-- HANZ SWING / WEEKLY ENGINE TABLES
-- Run once in Supabase SQL Editor.

create table if not exists public.hanz_swing_signal_monitor (
  ticker text primary key,
  state text not null default 'NO_SETUP',
  score integer,
  price numeric,
  daily_trend text,
  weekly_trend text,
  daily_rsi numeric,
  weekly_rsi numeric,
  daily_rvol numeric,
  breakout boolean not null default false,
  breakout_level numeric,
  stop_loss numeric,
  target_1 numeric,
  target_2 numeric,
  evidence text,
  daily_bar_at timestamptz,
  weekly_bar_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.hanz_swing_signal_monitor
enable row level security;

drop policy if exists "HANZ swing monitor public read"
on public.hanz_swing_signal_monitor;

create policy "HANZ swing monitor public read"
on public.hanz_swing_signal_monitor
for select
to anon, authenticated
using (true);

create index if not exists
hanz_swing_signal_monitor_state_idx
on public.hanz_swing_signal_monitor
(state, score desc);


create table if not exists public.hanz_swing_signals (
  id bigint generated by default as identity primary key,
  ticker text not null,
  signal_type text not null,
  price numeric,
  score integer,
  stop_loss numeric,
  target_1 numeric,
  target_2 numeric,
  reason text,
  created_at timestamptz not null default now()
);

alter table public.hanz_swing_signals
enable row level security;

drop policy if exists "HANZ swing signals public read"
on public.hanz_swing_signals;

create policy "HANZ swing signals public read"
on public.hanz_swing_signals
for select
to anon, authenticated
using (true);

create index if not exists
hanz_swing_signals_ticker_created_idx
on public.hanz_swing_signals
(ticker, created_at desc);
